### ISSUE TITLE
Facial Landmark - Make Error

### ISSUE THREAD

**Issue by LightBreakfast** [NVIDIA-AI-IOT/deepstream_tlt_apps#45]
Hi, I am attempting to build and run the Facial Landmark App. But encourtering the following problem. I am running this in the DeepStream 6 container image.

 ```
root@jn-dev-01:/opt/nvidia/deepstream/deepstream-6.0/deepstream_tao_apps/apps/tao_others/deepstream-faciallandmark-app# make
g++ -c -o deepstream_faciallandmark_app.o -fpermissive -Wall -Werror -DPLATFORM_TEGRA -I/opt/nvidia/deepstream/deepstream/sources/includes -I/opt/nvidia/deepstream/deepstream/sources/includes/cvcore_headers -I /usr/local/cuda-10.2/include `pkg-config --cflags gstreamer-1.0` -D_GLIBCXX_USE_CXX11_ABI=1 -Wno-sign-compare deepstream_faciallandmark_app.cpp

In file included from deepstream_faciallandmark_app.cpp:36:0:
/opt/nvidia/deepstream/deepstream/sources/includes/nvdsinfer_custom_impl.h:375:19: error: 'IPluginFactory' in namespace 'nvcaffeparser1' does not name a type
   nvcaffeparser1::IPluginFactory *pluginFactory;
                   ^~~~~~~~~~~~~~

/opt/nvidia/deepstream/deepstream/sources/includes/nvdsinfer_custom_impl.h:376:19: error: 'IPluginFactoryExt' in namespace 'nvcaffeparser1' does not name a type
   nvcaffeparser1::IPluginFactoryExt *pluginFactoryExt;
                   ^~~~~~~~~~~~~~~~~

/opt/nvidia/deepstream/deepstream/sources/includes/nvdsinfer_custom_impl.h:386:16: error: 'IPluginFactory' in namespace 'nvuffparser' does not name a type
   nvuffparser::IPluginFactory *pluginFactory;
                ^~~~~~~~~~~~~~

/opt/nvidia/deepstream/deepstream/sources/includes/nvdsinfer_custom_impl.h:387:16: error: 'IPluginFactoryExt' in namespace 'nvuffparser' does not name a type
   nvuffparser::IPluginFactoryExt *pluginFactoryExt;
                ^~~~~~~~~~~~~~~~~

Makefile:69: recipe for target 'deepstream_faciallandmark_app.o' failed
make: *** [deepstream_faciallandmark_app.o] Error 1
```

Running on an NVIDIA Jetson Nano

**Comment by This-Is-Not-Brad** [comment]
Was running JetPack 4.6. Make works on 4.5.1
